### ISSUE TITLE
Add unix timestamp to spark timestamp converter for the mapper transformer

### ISSUE THREAD

**Issue by Selbstsesslingen** [Breaka84/Spooq#3]
currently only conversions from unix timestamps (longtype) in ms or sec to unix timestamps (longtype) in ms or sec are supported. Needed conversions:
- unix timestamp in ms > spark timestamp
- unix timestamp in s > spark timestamp

**Comment by Breaka84** [comment]
https://github.com/Breaka84/Spooq/pull/8
